In [1]:
import numpy as np

In [2]:
marks = np.array([55,68,72,49,83,91,37,65,78,59,88])
print(marks)


[55 68 72 49 83 91 37 65 78 59 88]


In [3]:
print(marks[0])

55


In [4]:
print(marks[1:5])

[68 72 49 83]


In [6]:
marks[0:3] = 75
print(marks)

[75 75 75 49 83 91 37 65 78 59 88]


In [7]:
result = marks + 5
print(result)   

[80 80 80 54 88 96 42 70 83 64 93]


In [8]:
marks = np.array([55,68,49,83,91,37,65,78,59,88])
top_batch = marks[0:5]
print(top_batch)

[55 68 49 83 91]


In [10]:
top_batch[:] = 99
print(top_batch)
print(marks)

[99 99 99 99 99]
[99 99 99 99 99 37 65 78 59 88]


In [12]:
marks = np.array([55,68,49,83,91,37,65,78,59,88])
marks_copy = marks.copy()
marks_copy[3] = 100
print(marks)
print(marks_copy)

[55 68 49 83 91 37 65 78 59 88]
[ 55  68  49 100  91  37  65  78  59  88]


In [14]:
marks = np.array([69,26,78,91,54,34])
passed = marks >= 35
print(passed)
print(marks[passed])

[ True False  True  True  True False]
[69 78 91 54]


In [15]:
print(marks[marks >= 35])

[69 78 91 54]
