In [1]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(arr + arr)
print(arr * arr)
print(arr - arr)
print(arr / arr)
print(arr ** 2)
print(np.sqrt(arr))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_14000\1304369750.py:4: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)


In [3]:
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())
print(arr.var())

45
4.5
2.8722813232690143
9
0
8.25


In [4]:
students = np.array([
    ('Alice', 85, 20),
    ('Bob', 90, 22),
    ('Charlie', 78, 19)
],   dtype=[('name', 'U10'), ('marks', 'i4'), ('age', 'i4')])

print(students['name'])
print(students['marks'])
print(students['marks'].mean())
print(students[students['name'] == 'Bob']['marks'])
print(students[students['name'] == 'Bob']['marks'][0])

['Alice' 'Bob' 'Charlie']
[85 90 78]
84.33333333333333
[90]
90


In [5]:
sales = [0,5,155,0,518,616]
sales_array = np.array(sales)

print(type(sales_array))
print(sales_array.dtype)
print(sales_array.shape)
print(sales_array.ndim)
print(sales_array.size)

<class 'numpy.ndarray'>
int64
(6,)
1
6


In [6]:
result = np.where(sales_array == 0, 'No Sales', 'Sales Made')
print(result)

['No Sales' 'Sales Made' 'Sales Made' 'No Sales' 'Sales Made' 'Sales Made']


In [8]:
bool_mask = sales_array != 0
print(bool_mask)

[False  True  True False  True  True]


In [9]:
filtered_sales = sales_array[bool_mask]
print(filtered_sales)

[  5 155 518 616]
