In [2]:
import numpy as np

virat_runs = np.array([72,45,88,101])
print(virat_runs)

team_runs = np.array([
    [72,45,88],     #Virat
    [55,60,47],     #Rohit
    [30,75,50]      #Rahul
    ])

print(team_runs)

player_ages = np.array((35,37,31))

print(player_ages)

zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((3,2))
print(ones)

identify = np.eye(3)
print(identify)

empty = np.empty((2,4))
print(empty)

full = np.full((2,2),7)
print(full)

arr1 = np.arange(55,65)
print(arr1)

[ 72  45  88 101]
[[72 45 88]
 [55 60 47]
 [30 75 50]]
[35 37 31]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7]
 [7 7]]
[55 56 57 58 59 60 61 62 63 64]


In [3]:
run_rates = np.arange(4,11,1)
print(run_rates)

[ 4  5  6  7  8  9 10]


In [12]:
checks = np.linspace(1,10,4)
for i in checks:
    print(i)

1.0
4.0
7.0
10.0


In [13]:
batting_avgs = np.linspace(30,50,5)
print(batting_avgs)

[30. 35. 40. 45. 50.]


In [14]:
strike_rates = np.random.uniform(100,200,10)
print(strike_rates)

[193.38957777 143.38094689 144.45441529 114.31164687 184.70026716
 183.17239784 119.40107266 116.25308202 150.45460915 130.12411789]


In [ ]:
runs = np.random.randint(1,151,(2,3))

In [16]:
print(runs)

[ 78  35 143  57  60]


In [17]:
batting_avg = np.random.normal(35,7,(3,4))

In [18]:
print(batting_avg)

[[31.79043563 40.6205352  33.03979627 27.27284463]
 [33.55635466 35.93309632 35.44378318 30.01942042]
 [41.92719215 31.73609778 39.66532043 22.81095231]]


In [19]:
arr = np.arange(0,10)
new_arr_single = np.append(arr, 10)
new_arr_multiple = np.append(arr, [10,11,12])
print(arr)
print(new_arr_single)
print(new_arr_multiple)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
marks = np.arange(50,62)
print(marks)
reshaped = marks.reshape(3,4)
print(reshaped)

[50 51 52 53 54 55 56 57 58 59 60 61]
[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]]
